routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});




Auth::routes();

Route::get('login/facebook', 'Auth\SocialAuthFacebookController@redirectToFacebook');
Route::get('login/facebook/callback', 'Auth\SocialAuthFacebookController@handleFacebookCallback');

Route::get('login/google', 'Auth\SocialAuthGoogleController@redirectToGoogle');
Route::get('/callback', 'Auth\SocialAuthGoogleController@handleGoogleCallback');

Route::get('login/github', 'Auth\SocialAuthGithubController@redirectToGithub');
Route::get('/login/github/callback', 'Auth\SocialAuthGithubController@handleGithubCallback');


Route::middleware('auth')->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/products/add', 'ProductController@add')->name('products.add');

    Route::resource('products', 'ProductController')->except('create');

});

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Entity\Product;
use App\Http\Requests\ProductRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ProductController extends Controller
{
    public function index()
    {
        $products = Product::latest()->paginate(10);

        return view('product.index', compact('products'));
    }

    public function show($id)
    {
        $product = Product::find($id);

        return view('product.show', compact('product'));
    }

    public function add()
    {
        return view('product.add');
    }

    public function store(ProductRequest $request)
    {
        Product::create([
            'name' => $request->input('name'),
            'price' => $request->input('price'),
            'user_id' => Auth::id(),
        ]);

        return redirect('/products');
    }

    public function edit($id)
    {
        $product = Product::find($id);

        if (\request()->user()->can('view', $product)) {
            return view('product.edit', compact('product'));
        } else {
            return redirect()->to('/products');
        }

    }

    public function update(ProductRequest $request, $id)
    {
        $product = Product::find($id);

        $product->name = $request->input('name');
        $product->price = $request->input('price');

        $product->save();

        return redirect('/products/'.$product->id);
    }

    public function destroy($id)
    {
        $product = Product::find($id);
        $product->delete();

        return redirect('/products');
    }

}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Marketplace
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/product/add.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Add product</h1>
        <div class="row justify-content-md-center">
            <div class="col-md-6">
                <form action="{{ route('products.store') }}" method="post">
                    @csrf

                    @error('name')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror

                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" name="name" class="form-control" id="name">
                    </div>

                    @error('price')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror

                    <div class="form-group">
                        <label for="price">Price</label>
                        <input type="text" name="price" class="form-control" id="price">
                    </div>

                    <button type="submit" class="btn btn-primary">Save</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Edit product</h1>
        <div class="row justify-content-md-center">
            <div class="col-md-6">
                <form action="/products/{{ $product->id }}" method="post">
                    @csrf
                    @method("PUT")

                    @error('name')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror

                    <div class="form-group">
                        <label for="name">Name:</label>
                        <input type="text" name="name" class="form-control" id="name" value="{{ $product->name }}" >
                    </div>

                    @error('price')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror

                    <div class="form-group">
                        <label for="price">Price:</label>
                        <input type="text" name="price" class="form-control" id="price" value="{{ $product->price }}">
                    </div>

                    <button type="submit" class="btn btn-primary">Save</button>

                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/product/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-between">
            <h1>Product list</h1>
            <div class="col-4">
                <a href="{{ route('products.add') }}" class="btn btn-primary offset-md-4">Add product</a>
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-6">
                @foreach($products as $product)
                    <div class="card">
                        <div class="card-body">
                            <a href="{{ route('products.show', $product->id) }}">
                                <h3 class="card-text"> <strong>name:</strong> {{ $product->name }}</h3>
                            </a>
                            <p class="card-text"> <strong>price:</strong> {{ $product->price }}</p>
                        </div>
                    </div>
                @endforeach
            <div class="mt-3">
                {{ $products->links() }}
            </div>
            </div>
        </div>
    </div>
@endsection

resources/views/product/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Product page</h1>
        <div class="row justify-content-md-center">
            <div class="col-md-6">
                <div class="card mb-3">
                    <div class="card-body d-flex justify-content-between">
                        <div>
                            <h3 class="card-text"> <strong>name:</strong> {{ $product->name }}</h3>
                            <p class="card-text"> <strong>price:</strong> {{ $product->price }}</p>
                        </div>
                        <div>
                            @can('update', $product)
                                <div class="mb-2">
                                    <a href="{{ route('products.edit', $product->id) }}" class="btn btn-warning">Edit</a>
                                </div>

                                <form action="{{ route('products.destroy', $product->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')

                                    <button type="submit" class="btn badge-danger">Delete</button>
                                </form>
                            @endcan
                        </div>
                    </div>
                </div>
                <a href="{{ route('products.index') }}" class="btn btn-secondary">Back</a>
            </div>
        </div>
    </div>
@endsection